"""Export generator for ready-to-run notebooks and scripts.

Creates standalone Python scripts and Jupyter notebooks that users can run independently.
"""
import json
from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime


class ExportGenerator:
    """Generates ready-to-run code exports for advanced users."""
    
    TEMPLATE_HEADER = '''"""
AutoDS Generated Analysis Script
================================
Generated: {timestamp}
Dataset: {dataset_name}
Rows: {n_rows}, Columns: {n_cols}

This script was automatically generated by AutoDS and contains
all the code needed to reproduce your analysis.

Simply run: python analysis_script.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Configuration
DATA_PATH = "{data_path}"
OUTPUT_DIR = Path("analysis_output")
OUTPUT_DIR.mkdir(exist_ok=True)

print("=" * 60)
print("AutoDS Analysis Script")
print("=" * 60)
'''
    
    @staticmethod
    def generate_python_script(
        df_info: Dict[str, Any],
        preprocessing_config: Optional[Dict] = None,
        model_config: Optional[Dict] = None,
        include_comments: bool = True
    ) -> str:
        """Generate a standalone Python script."""
        
        lines = []
        
        # Header
        lines.append(ExportGenerator.TEMPLATE_HEADER.format(
            timestamp=datetime.now().isoformat(),
            dataset_name=df_info.get('name', 'dataset'),
            n_rows=df_info.get('n_rows', 0),
            n_cols=df_info.get('n_cols', 0),
            data_path=df_info.get('path', 'data.csv')
        ))
        
        # Data loading section
        lines.append('''
# ============================================
# 1. LOAD DATA
# ============================================

print("\\n📊 Loading data...")
df = pd.read_csv(DATA_PATH)
print(f"Loaded {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"\\nColumn names: {list(df.columns)}")
print(f"\\nData types:")
print(df.dtypes)
''')
        
        # Preprocessing section
        if preprocessing_config:
            lines.append('''
# ============================================
# 2. PREPROCESSING
# ============================================

print("\\n🔧 Preprocessing...")
''')
            
            if preprocessing_config.get('handle_missing'):
                strategy = preprocessing_config.get('missing_strategy', 'median')
                lines.append(f'''
# Handle missing values
print("  - Handling missing values (strategy: {strategy})...")
numeric_cols = df.select_dtypes(include=[np.number]).columns
if len(numeric_cols) > 0:
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].{strategy}())
categorical_cols = df.select_dtypes(include=['object']).columns
if len(categorical_cols) > 0:
    df[categorical_cols] = df[categorical_cols].fillna('Unknown')
''')
            
            if preprocessing_config.get('encode_categorical'):
                lines.append('''
# Encode categorical variables
print("  - Encoding categorical variables...")
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if col != target_col:  # Don't encode target
        df[col] = pd.Categorical(df[col]).codes
''')
            
            if preprocessing_config.get('drop_duplicates'):
                lines.append('''
# Remove duplicates
n_before = len(df)
df = df.drop_duplicates()
print(f"  - Removed {n_before - len(df)} duplicate rows")
''')
            
            lines.append('''
print(f"Processed data shape: {df.shape}")
''')
        
        # Modeling section
        if model_config and model_config.get('target_column'):
            target = model_config['target_column']
            task_type = model_config.get('task_type', 'classification')
            
            lines.append(f'''
# ============================================
# 3. MODEL TRAINING
# ============================================

print("\\n🤖 Training models...")
target_col = "{target}"
task_type = "{task_type}"

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Prepare features
X = df.drop(columns=[target_col])
y = df[target_col]

# Handle remaining categorical features
X = pd.get_dummies(X, drop_first=True)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y if task_type == "classification" else None
)

print(f"Training set: {X_train.shape[0]} samples")
print(f"Test set: {X_test.shape[0]} samples")

# Train models based on task type
if task_type == "classification":
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.linear_model import LogisticRegression
    
    models = {{
        "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42)
    }}
else:
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.linear_model import Ridge
    
    models = {{
        "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
        "Ridge Regression": Ridge(random_state=42)
    }}

results = {{}}
for name, model in models.items():
    print(f"\\n  Training {{name}}...")
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    score = model.score(X_test, y_test)
    results[name] = {{"score": score, "model": model}}
    print(f"    Score: {{score:.4f}}")

# Find best model
best_model_name = max(results, key=lambda x: results[x]["score"])
print(f"\\n🏆 Best model: {{best_model_name}} (score: {{results[best_model_name]['score']:.4f}})")
''')
        
        # Visualization section
        lines.append('''
# ============================================
# 4. VISUALIZATIONS
# ============================================

print("\\n📈 Creating visualizations...")

# Distribution of numeric columns
numeric_cols = df.select_dtypes(include=[np.number]).columns[:5]
if len(numeric_cols) > 0:
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    axes = axes.flatten()
    
    for i, col in enumerate(numeric_cols[:6]):
        df[col].hist(ax=axes[i], bins=30, edgecolor='black')
        axes[i].set_title(f'Distribution of {col}')
        axes[i].set_xlabel(col)
        axes[i].set_ylabel('Frequency')
    
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / 'distributions.png', dpi=150, bbox_inches='tight')
    print("  - Saved: distributions.png")
    plt.close()

# Correlation heatmap (if enough numeric columns)
if len(numeric_cols) > 2:
    plt.figure(figsize=(10, 8))
    corr = df[numeric_cols].corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm', center=0, fmt='.2f')
    plt.title('Correlation Matrix')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / 'correlation_matrix.png', dpi=150, bbox_inches='tight')
    print("  - Saved: correlation_matrix.png")
    plt.close()
''')
        
        # Footer
        lines.append('''
# ============================================
# 5. SAVE RESULTS
# ============================================

print("\\n💾 Saving results...")

# Save processed data
df.to_csv(OUTPUT_DIR / 'processed_data.csv', index=False)
print(f"  - Saved: processed_data.csv ({df.shape[0]} rows)")

# Save summary statistics
summary = df.describe()
summary.to_csv(OUTPUT_DIR / 'summary_statistics.csv')
print("  - Saved: summary_statistics.csv")

print("\\n" + "=" * 60)
print("✅ Analysis complete!")
print(f"📁 Results saved to: {OUTPUT_DIR.absolute()}")
print("=" * 60)
''')
        
        return '\n'.join(lines)
    
    @staticmethod
    def generate_jupyter_notebook(
        df_info: Dict[str, Any],
        preprocessing_config: Optional[Dict] = None,
        model_config: Optional[Dict] = None
    ) -> Dict:
        """Generate a Jupyter notebook as a dictionary."""
        
        cells = []
        
        # Title cell
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"# AutoDS Analysis Notebook\n",
                f"\n",
                f"**Generated:** {datetime.now().isoformat()}\n",
                f"**Dataset:** {df_info.get('name', 'dataset')}\n",
                f"**Shape:** {df_info.get('n_rows', 0):,} rows × {df_info.get('n_cols', 0)} columns\n",
                f"\n",
                f"This notebook was automatically generated by AutoDS and contains all the code needed to reproduce your analysis."
            ]
        })
        
        # Setup cell
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from pathlib import Path\n",
                "\n",
                "# Configuration\n",
                f"DATA_PATH = '{df_info.get('path', 'data.csv')}'\n",
                "OUTPUT_DIR = Path('analysis_output')\n",
                "OUTPUT_DIR.mkdir(exist_ok=True)\n",
                "\n",
                "# Plot style\n",
                "plt.style.use('seaborn-v0_8')\n",
                "sns.set_palette('husl')\n",
                "\n",
                "print('Libraries loaded successfully')"
            ],
            "outputs": []
        })
        
        # Load data cell
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 1. Load and Explore Data"]
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Load the dataset\n",
                "df = pd.read_csv(DATA_PATH)\n",
                "\n",
                "print(f'Dataset shape: {df.shape}')\n",
                "print(f'\\nColumn names: {list(df.columns)}')\n",
                "print('\\nFirst few rows:')\n",
                "df.head()"
            ],
            "outputs": []
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Data info\n",
                "df.info()\n",
                "\n",
                "# Summary statistics\n",
                "df.describe()"
            ],
            "outputs": []
        })
        
        # Preprocessing section
        if preprocessing_config:
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 2. Preprocessing"]
            })
            
            code_lines = ["# Preprocessing steps\n"]
            
            if preprocessing_config.get('handle_missing'):
                strategy = preprocessing_config.get('missing_strategy', 'median')
                code_lines.extend([
                    "# Handle missing values\n",
                    f"numeric_cols = df.select_dtypes(include=[np.number]).columns\n",
                    f"df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].{strategy}())\n",
                    "categorical_cols = df.select_dtypes(include=['object']).columns\n",
                    "df[categorical_cols] = df[categorical_cols].fillna('Unknown')\n",
                    "print(f'Missing values handled using {strategy} strategy')\n"
                ])
            
            if preprocessing_config.get('drop_duplicates'):
                code_lines.extend([
                    "\n# Remove duplicates\n",
                    "n_before = len(df)\n",
                    "df = df.drop_duplicates()\n",
                    "print(f'Removed {n_before - len(df)} duplicate rows')\n"
                ])
            
            code_lines.extend([
                "\nprint(f'Final shape: {df.shape}')\n",
                "df.head()"
            ])
            
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "source": code_lines,
                "outputs": []
            })
        
        # Modeling section
        if model_config and model_config.get('target_column'):
            target = model_config['target_column']
            task_type = model_config.get('task_type', 'classification')
            
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"## 3. Model Training ({task_type.title()})"]
            })
            
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "source": [
                    "from sklearn.model_selection import train_test_split\n",
                    "from sklearn.preprocessing import StandardScaler\n",
                    "\n",
                    f"target_col = '{target}'\n",
                    f"task_type = '{task_type}'\n",
                    "\n",
                    "# Prepare features\n",
                    "X = df.drop(columns=[target_col])\n",
                    "y = df[target_col]\n",
                    "\n",
                    "# Handle categorical features\n",
                    "X = pd.get_dummies(X, drop_first=True)\n",
                    "\n",
                    "# Split data\n",
                    "X_train, X_test, y_train, y_test = train_test_split(\n",
                    "    X, y, test_size=0.2, random_state=42\n",
                    ")\n",
                    "\n",
                    "print(f'Training set: {X_train.shape[0]} samples')\n",
                    "print(f'Test set: {X_test.shape[0]} samples')\n",
                    "print(f'Features: {X.shape[1]}')"
                ],
                "outputs": []
            })
            
            if task_type == "classification":
                cells.append({
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "source": [
                        "from sklearn.ensemble import RandomForestClassifier\n",
                        "from sklearn.linear_model import LogisticRegression\n",
                        "from sklearn.metrics import classification_report, accuracy_score\n",
                        "\n",
                        "models = {\n",
                        "    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),\n",
                        "    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42)\n",
                        "}\n",
                        "\n",
                        "results = {}\n",
                        "for name, model in models.items():\n",
                        "    print(f'\\nTraining {name}...')\n",
                        "    model.fit(X_train, y_train)\n",
                        "    predictions = model.predict(X_test)\n",
                        "    accuracy = accuracy_score(y_test, predictions)\n",
                        "    results[name] = {'accuracy': accuracy, 'model': model}\n",
                        "    print(f'Accuracy: {accuracy:.4f}')\n",
                        "\n",
                        "# Best model\n",
                        "best = max(results, key=lambda x: results[x]['accuracy'])\n",
                        "print(f'\\n🏆 Best model: {best}')"
                    ],
                    "outputs": []
                })
            else:
                cells.append({
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "source": [
                        "from sklearn.ensemble import RandomForestRegressor\n",
                        "from sklearn.linear_model import Ridge\n",
                        "from sklearn.metrics import r2_score, mean_squared_error\n",
                        "\n",
                        "models = {\n",
                        "    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42),\n",
                        "    'Ridge Regression': Ridge(random_state=42)\n",
                        "}\n",
                        "\n",
                        "results = {}\n",
                        "for name, model in models.items():\n",
                        "    print(f'\\nTraining {name}...')\n",
                        "    model.fit(X_train, y_train)\n",
                        "    predictions = model.predict(X_test)\n",
                        "    r2 = r2_score(y_test, predictions)\n",
                        "    rmse = np.sqrt(mean_squared_error(y_test, predictions))\n",
                        "    results[name] = {'r2': r2, 'rmse': rmse, 'model': model}\n",
                        "    print(f'R²: {r2:.4f}, RMSE: {rmse:.4f}')\n",
                        "\n",
                        "# Best model\n",
                        "best = max(results, key=lambda x: results[x]['r2'])\n",
                        "print(f'\\n🏆 Best model: {best}')"
                    ],
                    "outputs": []
                })
        
        # Visualization section
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 4. Visualizations"]
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Distribution plots\n",
                "numeric_cols = df.select_dtypes(include=[np.number]).columns[:6]\n",
                "\n",
                "if len(numeric_cols) > 0:\n",
                "    fig, axes = plt.subplots(2, 3, figsize=(15, 10))\n",
                "    axes = axes.flatten()\n",
                "    \n",
                "    for i, col in enumerate(numeric_cols):\n",
                "        df[col].hist(ax=axes[i], bins=30, edgecolor='black')\n",
                "        axes[i].set_title(f'Distribution of {col}')\n",
                "    \n",
                "    plt.tight_layout()\n",
                "    plt.show()\n"
            ],
            "outputs": []
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Correlation heatmap\n",
                "if len(numeric_cols) > 2:\n",
                "    plt.figure(figsize=(10, 8))\n",
                "    corr = df[numeric_cols].corr()\n",
                "    sns.heatmap(corr, annot=True, cmap='coolwarm', center=0)\n",
                "    plt.title('Correlation Matrix')\n",
                "    plt.tight_layout()\n",
                "    plt.show()\n"
            ],
            "outputs": []
        })
        
        # Footer
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Export Results\n",
                "\n",
                "Save processed data and results:"
            ]
        })
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Save processed data\n",
                "df.to_csv(OUTPUT_DIR / 'processed_data.csv', index=False)\n",
                "\n",
                "# Save summary\n",
                "df.describe().to_csv(OUTPUT_DIR / 'summary_statistics.csv')\n",
                "\n",
                "print(f'✅ Results saved to: {OUTPUT_DIR.absolute()}')\n",
                "print(f'📊 Processed data: {df.shape[0]} rows')"
            ],
            "outputs": []
        })
        
        # Create notebook structure
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "name": "python",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
        
        return notebook
    
    @staticmethod
    def save_python_script(script: str, path: str):
        """Save a Python script to file."""
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w') as f:
            f.write(script)
    
    @staticmethod
    def save_jupyter_notebook(notebook: Dict, path: str):
        """Save a Jupyter notebook to file."""
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w') as f:
            json.dump(notebook, f, indent=2)


def generate_analysis_exports(
    df_info: Dict[str, Any],
    output_dir: str = "exports",
    preprocessing_config: Optional[Dict] = None,
    model_config: Optional[Dict] = None
) -> Dict[str, str]:
    """Generate both Python script and Jupyter notebook exports."""
    
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate Python script
    script = ExportGenerator.generate_python_script(
        df_info, preprocessing_config, model_config
    )
    script_path = output_path / "analysis_script.py"
    ExportGenerator.save_python_script(script, str(script_path))
    
    # Generate Jupyter notebook
    notebook = ExportGenerator.generate_jupyter_notebook(
        df_info, preprocessing_config, model_config
    )
    notebook_path = output_path / "analysis_notebook.ipynb"
    ExportGenerator.save_jupyter_notebook(notebook, str(notebook_path))
    
    return {
        "python_script": str(script_path),
        "jupyter_notebook": str(notebook_path)
    }
